# Generated by Django 4.0.4 on 2022-05-16 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patien_phone'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprescription',
            name='created_By',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='eprescription',
            name='record',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='record.elrecord'),
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=400)),
                ('Epres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.eprescription')),
            ],
        ),
    ]
