# Generated by Django 4.0.4 on 2022-05-16 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0002_eprescription_created_by_eprescription_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eprescription',
            name='created_By',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
