# Generated by Django 4.0.4 on 2022-05-20 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0003_alter_eprescription_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elrecord',
            name='ER_created_by_doctor',
        ),
        migrations.AddField(
            model_name='elrecord',
            name='ER_doctor',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elrecord',
            name='ER_date_creation',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='elrecord',
            name='ER_patient',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
