# Generated by Django 4.0.4 on 2022-05-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_remove_elrecord_er_created_by_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elrecord',
            name='ER_date_creation',
        ),
    ]
